services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2025-CTP2.0-ubuntu-22.04
    environment:
      MSSQL_SA_PASSWORD: "SqlServer2025!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Evaluation"
    ports:
      - "1433:1433"